### ISSUE TITLE
Can attack monsters with knife in Angel of Marksmanship

### ISSUE THREAD

**Issue by Wuzzy2** [chaosforgeorg/doomrl#37] opened 2021-04-24 01:03 UTC
If you play Angel of Marksmanship but try attack a monster with a knife, you can actually perform the attack and deal damage. The message are screwed up, however. And if you kill a monster with the knife in this mode, you get an access violation.

This is the `error.log`:

```
----------------------------------------------------------------------
Timestamp   : 24-4-21 02:59:28
Error level : CRITICAL
Message     : Player action exception!

Error message : Access violation
----------------------------------------------------------------------
```

**Comment by RojjaCebolla** [comment] 2022-01-03 06:16
Perhaps add something like this line
https://github.com/chaosforgeorg/doomrl/blob/7db8b01539156a99930a43a5c97dc5f3c3f56196/bin/lua/challenge.lua#L107
to this code block?
https://github.com/chaosforgeorg/doomrl/blob/7db8b01539156a99930a43a5c97dc5f3c3f56196/bin/lua/challenge.lua#L213

**Comment by epyon** [comment] 2024-01-05 11:08
This is probably fixed in code, at least I cannot reproduce it :/

**Closed** 2024-01-05 11:13 UTC
